### ISSUE TITLE
service beacon

### ISSUE THREAD

**Issue by shadow-paw** [shadow-paw/lightcone#6]
use udp multicast to announce service

**Comment by iwasaki-kenta** [comment]
A layer-2 tunneling protocol would be necessary to utilize UDP multicast outside of your LAN. Hence, if you want to create a service beacon to remotely connect up servers in different data centers, it would be best to use other options such as ICE/other NAT traversal methods.

**Comment by shadow-paw** [comment]
In most deployment setup the servers should be on same network. In case of cloud server we could still setup openvpn to bridge them. Some cloud provider even support virtual network switch and they can access the multicast internally.

We can still design another HTTP-based directory lookup mechanic if multicast is not available, but it also introduce another single point failure.
